name: ci

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Get current date (week-based)
        id: get-date
        run: echo "WEEK=$(date +'%Y-%W')" >> $GITHUB_ENV

      - name: Cache apt packages
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/*.yml', '**/*.yaml') }}-${{ env.WEEK }}
          restore-keys: |
            ${{ runner.os }}-apt-${{ hashFiles('**/*.yml', '**/*.yaml') }}

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}-${{ env.WEEK }}
          restore-keys: |
            ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Deploy to GitHub Pages
        run: pipenv run deploy
