name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex
          pip install pipenv
          pipenv install --deploy --ignore-pipfile

      - name: Generate PDF
        run: |
          pipenv run pdfgen

      - name: Build MkDocs site
        run: |
          pipenv run build

      # - name: Setup Pages
      #   uses: actions/configure-pages@v3

      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v2
      #   with:
      #     # Upload entire repository
      #     path: "./site"

      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v2

      - name: Deploy to GitHub Pages
        uses: mikeal/publish-to-github-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: site
